apiVersion: apps/v1
kind: Deployment
metadata:
    name: corrin-demo
    labels:
        app: corrin-demo
spec:
    replicas: 2
    selector:
        matchLabels: 
            app: corrin-demo
    template:
        metadata:
            labels:
                app: corrin-demo
        spec:
            containers:
            -   name: corrin-demo
                image: cmcourvill/corrin-demo1
                ports:
                -   containerPort: 3000 
                resources:
                    limits:
                        memory: '128Mi'
                        cpu: '200m'
                livenessProbe:
                    httpGet:
                        path: /
                        port: 3000
                    initialDelaySeconds: 15
                    timeoutSeconds: 2
                    periodSeconds: 5
                    failureThreshold: 1
                readinessProbe:
                    httpGet:
                        path: /
                        port: 3000
                    initialDelaySeconds: 15
                    periodSeconds: 5
                    failureThreshold: 1